[versions]
androidx-compose = '1.0.0-beta04'
androidx-fragment = "1.3.3"
androidx-lifecycle = "2.3.1"
androidx-test = "1.3.0"
kotlin = "1.4.32"
navigation = "2.3.4"

[libraries]
androidx-activity-core = { group = "androidx.activity", name = "activity-ktx", version = "1.2.3" }
androidx-appcompat-core = { group = "androidx.appcompat", name = "appcompat", version = "1.3.0-rc01" }
androidx-constraintlayout-core = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.0.4" }
androidx-core = { group = "androidx.core", name = "core", version = "1.3.2" }
androidx-fragment-core = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }
androidx-fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "androidx-fragment" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version = "1.0.0-alpha10" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-runtime = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigation" }
androidx-test-core = { group = "androidx.test", name = "core-ktx", version.ref = "androidx-test" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version = "3.3.0" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version = "1.1.2" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-test" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test" }
androidx-test-truth = { group = "androidx.test.ext", name = "truth", version = "1.3.0" }
androidx-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "1.0.0-alpha04" }
androidx-viewmodel-core = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
google-truth = { group = "com.google.truth", name = "truth", version = "1.1.2" }
gradle-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-kotlinter = { group = "org.jmailen.gradle", name = "kotlinter-gradle", version = "3.4.0" }
gradle-plugin = { group = "com.android.tools.build", name = "gradle", version = "4.2.0" }
junit-core = { group = "junit", name = "junit", version = "4.13.2" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
robolectric-core = { group = "org.robolectric", name = "robolectric", version = "4.5.1" }
