name: CI
on: pull_request

jobs:

  ktlint:
    name: KTLint
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run KTLint
        run: bash ./gradlew lintKotlin

  buildHealth:
    name: Build Health
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run BuildHealth
#        run: bash ./gradlew buildHealth
        run: bash ./gradlew adviceDebug

  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit Tests
        run: bash ./gradlew testDebug --stacktrace

  buildApk:
    name: Build Sample APK
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew sample:assembleDebug --stacktrace
